### ISSUE TITLE
Review Request for AP-7 Agathis Trunk Standard

### ISSUE THREAD

**Issue by md-agathisproject** [agathis-project/pinus-rigida#1]
### Please review the AP-7 Agathis Trunk Standard 
      current commit 772ea9d
#### Need to two focus levels: 
   1. form 
   2. content

- the form needs to be judged against the guidelines in [AP-8](https://github.com/agathis-project/agathis-project/blob/master/AP-8/AP-8.md), consistency and readability. 

- the content needs to be judged against the root [schematic ](https://github.com/agathis-project/salix-arctica/blob/master/v1/SCH-1-1-1.pdf), root assembly [model ](https://github.com/agathis-project/salix-arctica/blob/master/v1/PCA-1-1-1.pdf)and your engineering experience.

- Review to be done by by adding comments to this issue; author will address every comment.
- Reviewer's comments need to start by indicating the commit they apply to.
- Work on the document under review may continue after review request issue opened.
- Author responsible for mitigating reviewers comments done at different commits.

- the amount of technical data to be covered is not small; there could be many questions; any question needs to be answered; this issue is a good tool for this purpose; fire your questions; I will answer.

In an ideal frictionless world, the review would happen instantly; in our shared reality, however - we need to deal with the friction - in its most manifested aspect - delays. So, I started rolling this ball; needs some more pushing at the beginning, then to take care it moves in the "right" direction. For now, just need to keep the ball rolling. So, I will keep pushing the ball and ask for help.  What this means for this review: I will keep working on the trunk standard as needed; I will review the doc myself and try to change hats as best as I can - author's hat and reviewer's hat. As a reviewer I should comment on the review request; then take the author's hat and answer the comment; then wait some - eventually going to the document and correct whatever needed. But I face my own frictions and tendencies for shortcuts - go directly to the doc and correct instantly.
Welcome to my reality :)

Reviewers:
@jonsnow1357 
@eemitev 
@md-agathisproject

**Comment by eemitev** [comment]
current commit 772ea9d

Test Feedback

How does ADDR bus work? More detail is needed about the way it is supposed to be used and what kind of information goes over those pins.

**Comment by md-agathisproject** [comment]
current commit 772ea9d
- how the **ADDR** works is defined in the function paragraph of INTSn, SENn, SPIA and SPIB circuits; 
- this organization was intended to make it easier for branch designer (if branch does not implement the INTSn,SENn,SPIA,SPIB, then no need to dig into how it works); I see now this makes life more difficult for the root or system designer.
- I will add a diagram+explanation at the "5.2. Control Circuits" level;
  - to make it even easier to understand and implement, the diagram will include a gate level implementation using physical of the shelf devices.

**Comment by md-agathisproject** [comment]
current commit 772ea9d

Function description for **SEn** is faulty (5.2.5.)

**Comment by md-agathisproject** [comment]
current commit 649be32

Updated AP doc with diagram and corrections to address last 3 comments.
