### ISSUE TITLE
Section 3.3.h.b

### ISSUE THREAD

**Issue by jonsnow1357** [agathis-project/pinus-rigida#16]
762c4bd62602ae0bd07c3ce07d4632d413271ab6

"In a computing architecture, some PCIe links need to work really fast, such as the ones used by GPU, while others are operated at lower speeds, called here the peripherals"

This is confusing.
- first of all aren't they PCIe lanes?
- the PCIe speed is always the same (2.5G or 5G or whatever  ...) I think we're referring to bandwidth here, and I think this should be reformulated

"A PE1X Peripheral module  MAY consume only the first link or all four"

I think we mean SHALL not MAY. But also why not allow 1, 2 or 4 lanes?

**Comment by md-agathisproject** [comment]
- the PCIe for GPU (and maybe SSD) is directly connected to the processor (Intel), while the others are connected through the chipset; the new commit 5b81173 evades this issue; the split between graphics and peripheral modules was somewhat artificial; the new topology is more permissive in this regard.
- the second part is debatable; P1X is made of 4 x1 links and meant for lower bandwidth applications compared to P16X; the strategy for P1X is to stay on 1x links and make them avail to as many modules as possible; if you want 4x links, upgrade to P16x; "...The goal of constraining the P1X/P16X topologies is a simplified architecture for a healthy ecosystem..." I'm not interested in promoting fringe architectures; they may be helpful later on, not now.
