### ISSUE TITLE
Spec Review: Section 1

### ISSUE THREAD

**Issue by jonsnow1357** [agathis-project/pinus-rigida#7]
277d4829d2d69fdd2d5cc2e695aa1e09ece4c450

## 1.5
simplify: drawings and diagrams are the same thing

## 1.7
what is the difference between byte values and hex values? probably better to remove byte values

**Comment by md-agathisproject** [comment]
1.5: to me, drawings are the technical type of, dimensions, numbers, etc...diagrams are more like block diagram to me
1.7: B like in "64B" 64bytes; h like in "55aah"
may need them both;

**Comment by jonsnow1357** [comment]
what is 64B???
- a hex number meaning 01100100b? 
- a decimal number meaning 0100000b? 
- actually 00000110b 00000100b meaning each character is a byte?

there is no mathematical byte number format
this is very confusing

**Comment by md-agathisproject** [comment]
how much memory do you have?
I have 64B

**Comment by jonsnow1357** [comment]
then Byte is a unit of measurement, not a number format

otherwise 15mm is a number format too

**Comment by md-agathisproject** [comment]
testing the following line
277d4829d2d69fdd2d5cc2e695aa1e09ece4c450

**Comment by md-agathisproject** [comment]
1.7. Numbers
i) Agreed to remove bytes.

ii) Are the b and h ok ? What format do you usually use for hex values in similar docs?

**Comment by jonsnow1357** [comment]
they're ok. If you really want you can have 0x for hex values. I have seen both ...

Maybe 0xABCD looks better than ABCDh, up to each person ...

**Comment by md-agathisproject** [comment]
doc updated 90a3ada536d29557efb9961de567e62e4a02272c
