### ISSUE TITLE
Spec Review: Section 2.1

### ISSUE THREAD

**Issue by jonsnow1357** [agathis-project/pinus-rigida#8]
277d4829d2d69fdd2d5cc2e695aa1e09ece4c450

## 2.1.a
could we add some dimensions?

## 2.1.c
remove mention to I2C-EEPROM

## 2.1.d
remove mention to I2C-EEPROM

**Comment by md-agathisproject** [comment]
agreed on all requests.

**Comment by md-agathisproject** [comment]
2.1.a pending
2.1.c and 2.1.d updated on 90a3ada536d29557efb9961de567e62e4a02272c

**Comment by md-agathisproject** [comment]
The issue has been addressed.
